<script setup lang="ts">
import { computed, watch } from 'vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
import { ArrowLeft, CalendarDays, CarFront, CheckCircle2, MapPin, ShieldCheck, Users } from 'lucide-vue-next';
import AppLayout from '@/layouts/AppLayout.vue';
import type { BreadcrumbItem } from '@/types';

type Vehicle={id:number;name:string;brand:string;model:string;type:string;seats:number;description:string|null;image:string|null;price:number;status:string};
const props=defineProps<{vehicles:Vehicle[];initial:{pickup_location:string;return_location:string;start_date:string;end_date:string;passengers:number}}>();
const minDate=new Date().toLocaleDateString('en-CA');
const form=useForm({customer_name:'',phone:'',email:'',pickup_location:props.initial.pickup_location,return_location:props.initial.return_location,start_date:props.initial.start_date,end_date:props.initial.end_date,passengers:Math.max(1,props.initial.passengers||1),vehicle_id:props.vehicles[0]?.id??null,notes:''});
const selectedVehicle=computed(()=>props.vehicles.find(v=>v?.id===form.vehicle_id)??null);
const passengerLimit=computed(()=>selectedVehicle.value?.seats??60);
watch(passengerLimit,limit=>{if(form.passengers>limit)form.passengers=limit},{immediate:true});
watch(()=>form.start_date,date=>{if(date&&(!form.end_date||form.end_date<date))form.end_date=date});
const breadcrumbs:BreadcrumbItem[]=[{title:'Thuê xe',href:'/thue-xe'}];
const submit=()=>form.post('/thue-xe');
</script>
<template>
<AppLayout :breadcrumbs="breadcrumbs"><Head title="Thuê xe"/>
<div class="min-w-0 bg-gradient-to-b from-sky-50/70 via-background to-background p-3 sm:p-6 lg:p-8"><div class="mx-auto max-w-6xl">
  <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Link href="/" class="inline-flex items-center gap-1.5 text-sm font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft class="size-4"/> Trang chủ</Link><div class="mt-3 flex items-center gap-3"><span class="grid size-11 place-items-center rounded-2xl bg-primary text-primary-foreground shadow-lg shadow-primary/20"><CarFront class="size-6"/></span><div><p class="text-xs font-bold uppercase tracking-widest text-primary">Thuê xe</p><h1 class="text-2xl font-black tracking-tight sm:text-3xl">Thuê xe theo ngày</h1></div></div><p class="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Chọn xe, thời gian và điểm nhận trả. Nhân viên sẽ liên hệ xác nhận trước khi chốt.</p></div><div class="hidden items-center gap-2 rounded-full border bg-card px-4 py-2 text-xs font-semibold shadow-sm sm:flex"><ShieldCheck class="size-4 text-emerald-600"/> Không thanh toán online</div></div>
  <div class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><div class="min-w-0 rounded-3xl border bg-card p-4 shadow-sm sm:p-7">
    <form class="grid gap-5" @submit.prevent="submit"><div class="flex items-center gap-3 border-b pb-5"><div class="grid size-9 place-items-center rounded-xl bg-primary/10 text-primary font-bold">1</div><div><h2 class="font-bold">Thông tin người thuê</h2><p class="text-xs text-muted-foreground">Chúng tôi cần thông tin để liên hệ</p></div></div>
      <div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-1.5 text-sm font-medium">Họ và tên<input v-model="form.customer_name" required maxlength="120" placeholder="Nguyễn Văn A" class="rounded-xl border bg-background px-3.5 py-3"/><span v-if="form.errors.customer_name" class="text-xs text-destructive">{{form.errors.customer_name}}</span></label><label class="grid gap-1.5 text-sm font-medium">Số điện thoại<input v-model="form.phone" required inputmode="tel" placeholder="09xx xxx xxx" class="rounded-xl border bg-background px-3.5 py-3"/><span v-if="form.errors.phone" class="text-xs text-destructive">{{form.errors.phone}}</span></label></div>
      <label class="grid gap-1.5 text-sm font-medium">Email<input v-model="form.email" required type="email" placeholder="email@example.com" class="rounded-xl border bg-background px-3.5 py-3"/><span v-if="form.errors.email" class="text-xs text-destructive">{{form.errors.email}}</span></label>
      <div class="border-t pt-5"><div class="mb-4 flex items-center gap-3"><div class="grid size-9 place-items-center rounded-xl bg-primary/10 text-primary font-bold">2</div><div><h2 class="font-bold">Thời gian & địa điểm</h2><p class="text-xs text-muted-foreground">Thời gian thuê và nơi nhận trả xe</p></div></div><div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-1.5 text-sm font-medium">Ngày bắt đầu<div class="flex items-center gap-2 rounded-xl border bg-background px-3.5 py-3"><CalendarDays class="size-4 shrink-0 text-primary"/><input v-model="form.start_date" :min="minDate" required type="date" class="w-full border-0 bg-transparent p-0 text-sm outline-none focus:ring-0"/></div><span v-if="form.errors.start_date" class="text-xs text-destructive">{{form.errors.start_date}}</span></label><label class="grid gap-1.5 text-sm font-medium">Ngày kết thúc<div class="flex items-center gap-2 rounded-xl border bg-background px-3.5 py-3"><CalendarDays class="size-4 shrink-0 text-primary"/><input v-model="form.end_date" :min="form.start_date||minDate" required type="date" class="w-full border-0 bg-transparent p-0 text-sm outline-none focus:ring-0"/></div><span v-if="form.errors.end_date" class="text-xs text-destructive">{{form.errors.end_date}}</span></label></div><div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="grid gap-1.5 text-sm font-medium"><span class="flex items-center gap-1.5"><MapPin class="size-4 text-primary"/> Điểm nhận xe</span><input v-model="form.pickup_location" required maxlength="255" placeholder="Địa chỉ nhận xe" class="rounded-xl border bg-background px-3.5 py-3"/><span v-if="form.errors.pickup_location" class="text-xs text-destructive">{{form.errors.pickup_location}}</span></label><label class="grid gap-1.5 text-sm font-medium"><span class="flex items-center gap-1.5"><MapPin class="size-4 text-primary"/> Điểm trả xe</span><input v-model="form.return_location" required maxlength="255" placeholder="Địa chỉ trả xe" class="rounded-xl border bg-background px-3.5 py-3"/><span v-if="form.errors.return_location" class="text-xs text-destructive">{{form.errors.return_location}}</span></label></div></div>
      <div class="border-t pt-5"><div class="mb-4 flex items-center gap-3"><div class="grid size-9 place-items-center rounded-xl bg-primary/10 text-primary font-bold">3</div><div><h2 class="font-bold">Chọn xe</h2><p class="text-xs text-muted-foreground">Tối đa {{passengerLimit}} hành khách với xe đang chọn</p></div></div><div class="grid gap-2.5"><div v-if="!props.vehicles.length" class="rounded-2xl border border-dashed p-4 text-sm text-muted-foreground">Hiện chưa có xe khả dụng.</div><label v-for="vehicle in props.vehicles" :key="vehicle.id" class="flex min-w-0 cursor-pointer gap-3 rounded-2xl border p-4 transition hover:bg-accent has-[:checked]:border-primary has-[:checked]:bg-primary/5"><input v-model="form.vehicle_id" :value="vehicle.id" type="radio" class="mt-1 shrink-0 accent-indigo-600"/><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center justify-between gap-2"><div class="truncate font-bold">{{vehicle.name}}</div><span class="rounded-full bg-muted px-2.5 py-1 text-xs font-semibold">{{vehicle.seats}} chỗ</span></div><div class="mt-1 text-xs text-muted-foreground">{{vehicle.brand}} {{vehicle.model}} · {{vehicle.type}}</div><p v-if="vehicle.description" class="mt-1 line-clamp-2 text-sm text-muted-foreground">{{vehicle.description}}</p></div></label></div></div>
      <label class="grid gap-1.5 text-sm font-medium">Số hành khách<div class="flex items-center gap-2 rounded-xl border bg-background px-3.5 py-3"><Users class="size-4 text-primary"/><input v-model.number="form.passengers" :min="1" :max="passengerLimit" required type="number" class="w-full border-0 bg-transparent p-0 outline-none focus:ring-0"/></div><span v-if="form.errors.passengers" class="text-xs text-destructive">{{form.errors.passengers}}</span></label>
      <label class="grid gap-1.5 text-sm font-medium">Ghi chú<textarea v-model="form.notes" maxlength="2000" placeholder="Yêu cầu thêm (nếu có)" class="min-h-24 rounded-xl border bg-background px-3.5 py-3"/></label>
      <div class="flex flex-col-reverse gap-2 border-t pt-5 sm:flex-row sm:justify-end"><Link href="/" class="rounded-xl border px-5 py-3 text-center text-sm font-semibold hover:bg-muted">Hủy</Link><button :disabled="form.processing||!selectedVehicle" type="submit" class="rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground shadow-lg shadow-primary/20 hover:-translate-y-0.5 disabled:opacity-50">{{form.processing?'Đang gửi...':'Gửi yêu cầu thuê xe'}}</button></div>
    </form></div>
    <aside class="min-w-0 lg:sticky lg:top-6 lg:self-start"><div class="overflow-hidden rounded-3xl border bg-slate-950 text-white shadow-xl"><div class="bg-gradient-to-br from-sky-600/40 to-indigo-500/10 p-6"><p class="text-xs font-bold uppercase tracking-widest text-sky-200">Tóm tắt thuê xe</p><h2 class="mt-2 break-words text-xl font-black">{{selectedVehicle?.name || 'Chưa chọn xe'}}</h2><p class="mt-2 text-sm text-slate-400">{{selectedVehicle ? `${selectedVehicle.seats} chỗ · ${selectedVehicle.type}` : 'Chọn một xe để xem thông tin'}}</p></div><div class="space-y-3 p-6 text-sm"><div class="flex items-center justify-between gap-3"><span class="text-slate-400">Từ ngày</span><span class="font-semibold">{{form.start_date || 'Chưa chọn'}}</span></div><div class="flex items-center justify-between gap-3"><span class="text-slate-400">Đến ngày</span><span class="font-semibold">{{form.end_date || 'Chưa chọn'}}</span></div><div class="flex items-center justify-between gap-3"><span class="text-slate-400">Hành khách</span><span class="font-semibold">{{form.passengers}} người</span></div><div v-if="selectedVehicle" class="mt-5 rounded-2xl border border-white/10 bg-white/5 p-4"><p class="text-xs text-slate-400">Giá tham khảo</p><p class="mt-1 text-lg font-black">{{Number(selectedVehicle.price).toLocaleString('vi-VN')}}đ/ngày</p></div><div class="mt-4 rounded-2xl border border-white/10 bg-white/5 p-4 text-xs leading-5 text-slate-400"><CheckCircle2 class="mb-2 size-5 text-emerald-400"/> Yêu cầu miễn phí. Giá cuối cùng và tình trạng xe sẽ được xác nhận trực tiếp.</div></div></div></aside>
  </div>
</div></div></AppLayout>
</template>
