<script setup lang="ts">
import { Head, Link, useForm, usePage } from '@inertiajs/vue3';
import { CalendarDays, CarFront, CheckCircle2, Mail, MapPin, Phone, Users } from '@lucide/vue';
import { computed, watch } from 'vue';
interface Vehicle { id:number; name:string; brand:string; model:string; type:string|null; seats:number; description:string|null; image:string|null; price:string|number; status:string; }
interface Initial { pickup_location:string; return_location:string; start_date:string; end_date:string; passengers:number; }
const props = defineProps<{ vehicles:Vehicle[]; initial:Initial }>();
const page = usePage();
const form = useForm({ customer_name:'', phone:'', email:'', vehicle_id:props.vehicles[0]?.id ?? null, start_date:props.initial.start_date, end_date:props.initial.end_date, pickup_location:props.initial.pickup_location, return_location:props.initial.return_location, passengers:Math.max(1, props.initial.passengers || 1), notes:'' });
const minDate = new Date().toISOString().slice(0,10);
const selectedVehicle = computed(() => props.vehicles.find((v) => v.id === form.vehicle_id));
const passengerLimit = computed(() => selectedVehicle.value?.seats ?? 60);
const success = computed(() => page.props.flash?.success as string|undefined);
watch(passengerLimit, (limit) => { if (form.passengers > limit) form.passengers = limit; });
const submit = () => form.post('/thue-xe', { preserveScroll:true, onSuccess:() => form.reset('customer_name','phone','email','start_date','end_date','pickup_location','return_location','notes') });
</script>
<template>
<Head title="Thuê xe" />
<div class="min-h-screen bg-slate-50 text-slate-950">
<header class="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div class="mx-auto flex h-16 max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8"><Link href="/" class="flex items-center gap-2 font-black"><span class="grid size-9 place-items-center rounded-xl bg-slate-950 text-white"><CarFront class="size-5" /></span><span>Car<span class="text-indigo-600">Booking</span></span></Link><nav class="hidden items-center gap-6 text-sm font-semibold md:flex"><Link href="/dat-xe" class="hover:text-indigo-600">Đặt xe</Link><Link href="/thue-xe" class="text-indigo-600">Thuê xe</Link><Link href="/tour" class="hover:text-indigo-600">Theo tour</Link><Link href="/blog" class="hover:text-indigo-600">Blog</Link></nav><Link href="/" class="text-sm font-semibold text-slate-500">Trang chủ</Link></div></header>
<main class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8 lg:py-10"><div class="mb-8"><p class="text-sm font-bold uppercase tracking-widest text-indigo-600">Thuê xe</p><h1 class="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Chọn xe cho hành trình của bạn</h1><p class="mt-2 max-w-2xl text-slate-500">Xem xe thực tế, chọn thời gian thuê và gửi yêu cầu. Không cần tài khoản, không thanh toán online.</p></div>
<div v-if="success" class="mb-6 flex items-start gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800"><CheckCircle2 class="mt-0.5 size-5" /><div><p class="font-bold">Gửi yêu cầu thành công</p><p class="mt-1 text-sm">{{ success }}</p></div></div><div v-if="form.errors.vehicle_id" class="mb-6 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{{ form.errors.vehicle_id }}</div>
<div class="grid gap-8 lg:grid-cols-[1fr_.9fr]"><section><div v-if="vehicles.length" class="grid gap-5 sm:grid-cols-2 xl:grid-cols-3"><button v-for="vehicle in vehicles" :key="vehicle.id" type="button" @click="form.vehicle_id=vehicle.id" class="overflow-hidden rounded-3xl border bg-white text-left shadow-sm transition hover:-translate-y-1 hover:shadow-lg" :class="form.vehicle_id===vehicle.id?'border-indigo-500 ring-2 ring-indigo-100':'border-slate-200'"><div class="relative aspect-[4/3] bg-slate-100"><img v-if="vehicle.image" :src="vehicle.image" :alt="vehicle.name" class="h-full w-full object-cover" /><div v-else class="grid h-full place-items-center"><CarFront class="size-16 text-slate-300" /></div><span class="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1 text-xs font-bold">Có sẵn</span></div><div class="p-5"><div class="flex items-start justify-between gap-3"><div><h2 class="text-lg font-black">{{ vehicle.name }}</h2><p class="mt-1 text-sm text-slate-500">{{ vehicle.brand }} · {{ vehicle.model }}</p></div><span v-if="form.vehicle_id===vehicle.id" class="rounded-full bg-indigo-600 p-1 text-white"><CheckCircle2 class="size-4" /></span></div><p class="mt-3 text-sm text-slate-600">{{ vehicle.seats }} chỗ · {{ vehicle.type || 'Xe dịch vụ' }}</p><p v-if="vehicle.description" class="mt-2 line-clamp-2 text-sm text-slate-500">{{ vehicle.description }}</p><p class="mt-4 text-base font-black">{{ Number(vehicle.price).toLocaleString('vi-VN') }}đ <span class="text-xs font-medium text-slate-400">/ngày</span></p></div></button></div><div v-else class="rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">Hiện chưa có xe khả dụng để thuê.</div></section>
<aside><form @submit.prevent="submit" class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6 lg:sticky lg:top-24"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Thông tin thuê</p><h2 class="mt-1 text-xl font-black">Đăng ký thuê xe</h2></div><span class="shrink-0 rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">Không cần đăng nhập</span></div><div class="mt-6 space-y-4">
<label><span class="mb-1.5 block text-sm font-semibold">Họ và tên <b class="text-rose-500">*</b></span><input v-model="form.customer_name" class="w-full rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100" /><p v-if="form.errors.customer_name" class="mt-1 text-xs text-rose-600">{{ form.errors.customer_name }}</p></label>
<label><span class="mb-1.5 block text-sm font-semibold">Số điện thoại <b class="text-rose-500">*</b></span><div class="flex items-center gap-2 rounded-2xl border border-slate-200 px-4 py-3"><Phone class="size-4 text-slate-400" /><input v-model="form.phone" type="tel" class="w-full border-0 p-0 outline-none focus:ring-0" placeholder="0901234567" /></div><p v-if="form.errors.phone" class="mt-1 text-xs text-rose-600">{{ form.errors.phone }}</p></label>
<label><span class="mb-1.5 block text-sm font-semibold">Email <b class="text-rose-500">*</b></span><div class="flex items-center gap-2 rounded-2xl border border-slate-200 px-4 py-3"><Mail class="size-4 text-slate-400" /><input v-model="form.email" type="email" class="w-full border-0 p-0 outline-none focus:ring-0" /></div><p v-if="form.errors.email" class="mt-1 text-xs text-rose-600">{{ form.errors.email }}</p></label>
<div class="rounded-2xl bg-slate-50 p-4"><p class="text-xs font-bold uppercase text-slate-400">Xe đã chọn</p><p class="mt-1 font-black">{{ selectedVehicle?.name || 'Chọn một xe bên trái' }}</p><p v-if="selectedVehicle" class="mt-1 text-sm text-slate-500">{{ selectedVehicle.seats }} chỗ · {{ selectedVehicle.brand }}</p></div>
<div class="grid gap-3 sm:grid-cols-2"><label><span class="mb-1.5 block text-sm font-semibold">Ngày bắt đầu <b class="text-rose-500">*</b></span><div class="flex items-center gap-2 rounded-2xl border border-slate-200 px-4 py-3"><CalendarDays class="size-4 text-indigo-600" /><input v-model="form.start_date" :min="minDate" type="date" class="w-full border-0 p-0 outline-none focus:ring-0" /></div><p v-if="form.errors.start_date" class="mt-1 text-xs text-rose-600">{{ form.errors.start_date }}</p></label><label><span class="mb-1.5 block text-sm font-semibold">Ngày kết thúc <b class="text-rose-500">*</b></span><div class="flex items-center gap-2 rounded-2xl border border-slate-200 px-4 py-3"><CalendarDays class="size-4 text-indigo-600" /><input v-model="form.end_date" :min="form.start_date || minDate" type="date" class="w-full border-0 p-0 outline-none focus:ring-0" /></div><p v-if="form.errors.end_date" class="mt-1 text-xs text-rose-600">{{ form.errors.end_date }}</p></label></div>
<div class="grid gap-3 sm:grid-cols-2"><label><span class="mb-1.5 block text-sm font-semibold">Điểm nhận xe <b class="text-rose-500">*</b></span><div class="flex items-center gap-2 rounded-2xl border border-slate-200 px-4 py-3"><MapPin class="size-4 text-indigo-600" /><input v-model="form.pickup_location" class="w-full border-0 p-0 outline-none focus:ring-0" /></div><p v-if="form.errors.pickup_location" class="mt-1 text-xs text-rose-600">{{ form.errors.pickup_location }}</p></label><label><span class="mb-1.5 block text-sm font-semibold">Điểm trả xe <b class="text-rose-500">*</b></span><div class="flex items-center gap-2 rounded-2xl border border-slate-200 px-4 py-3"><MapPin class="size-4 text-indigo-600" /><input v-model="form.return_location" class="w-full border-0 p-0 outline-none focus:ring-0" /></div><p v-if="form.errors.return_location" class="mt-1 text-xs text-rose-600">{{ form.errors.return_location }}</p></label></div>
<label><span class="mb-1.5 block text-sm font-semibold">Số lượng người <b class="text-rose-500">*</b></span><div class="flex items-center gap-2 rounded-2xl border border-slate-200 px-4 py-3"><Users class="size-4 text-indigo-600" /><select v-model="form.passengers" class="w-full border-0 bg-transparent p-0 outline-none focus:ring-0"><option v-for="n in passengerLimit" :key="n" :value="n">{{ n }} người</option></select></div><p v-if="form.errors.passengers" class="mt-1 text-xs text-rose-600">{{ form.errors.passengers }}</p></label>
<label><span class="mb-1.5 block text-sm font-semibold">Ghi chú</span><textarea v-model="form.notes" rows="3" class="w-full rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100" /></label>
<button :disabled="form.processing || !selectedVehicle" class="w-full rounded-2xl bg-indigo-600 px-5 py-3.5 font-bold text-white hover:bg-indigo-500 disabled:cursor-not-allowed disabled:opacity-60">{{ form.processing ? 'Đang gửi...' : 'Gửi yêu cầu thuê xe' }}</button><p class="text-center text-xs text-slate-400">Chúng tôi sẽ kiểm tra lịch xe và liên hệ xác nhận.</p>
</div></form></aside></div></main></div>
</template>
