<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3';
import { ArrowRight, BookOpen, CarFront, Sparkles } from '@lucide/vue';
interface Post { id:number; title:string; slug:string; excerpt:string|null; image:string|null; published_at:string|null; }
defineProps<{ posts:Post[] }>();
</script>
<template>
<Head title="Blog"/>
<div class="min-h-screen bg-slate-50 text-slate-950">
<header class="sticky top-0 z-30 border-b border-slate-200/80 bg-white/95 backdrop-blur"><div class="mx-auto flex min-h-16 max-w-7xl flex-wrap items-center justify-between gap-3 px-4 py-3 sm:px-6 lg:px-8"><Link href="/" class="flex items-center gap-2 font-black"><span class="grid size-9 shrink-0 place-items-center rounded-xl bg-indigo-600 text-white"><CarFront class="size-5"/></span><span>Car<span class="text-indigo-600">Booking</span></span></Link><nav class="hidden items-center gap-6 text-sm font-semibold md:flex"><Link href="/" class="hover:text-indigo-600">Trang chủ</Link><Link href="/dat-xe" class="hover:text-indigo-600">Đặt xe</Link><Link href="/thue-xe" class="hover:text-indigo-600">Thuê xe</Link><Link href="/tour" class="hover:text-indigo-600">Theo tour</Link><Link href="/blog" class="text-indigo-600">Blog</Link></nav><Link href="/dat-xe" class="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-indigo-600/20">Đặt xe</Link></div></header>
<main>
<section class="relative overflow-hidden bg-slate-950"><div class="absolute inset-0 bg-[radial-gradient(circle_at_15%_20%,rgba(59,130,246,.28),transparent_32%),radial-gradient(circle_at_85%_25%,rgba(99,102,241,.22),transparent_30%)]"/><div class="relative mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><div class="max-w-3xl text-white"><div class="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-3 py-1.5 text-xs font-bold"><Sparkles class="size-4 text-sky-300"/> KIẾN THỨC DI CHUYỂN</div><h1 class="mt-5 text-4xl font-black tracking-tight sm:text-5xl">Blog CarBooking</h1><p class="mt-4 max-w-2xl text-sm leading-7 text-slate-300 sm:text-lg">Kinh nghiệm đặt xe, thuê xe và chuẩn bị hành trình thuận tiện, chủ động hơn.</p></div></div></section>
<section class="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8 lg:py-14"><div v-if="posts.length" class="grid gap-5 sm:grid-cols-2 xl:grid-cols-3"><article v-for="post in posts" :key="post.id" class="group flex min-w-0 flex-col overflow-hidden rounded-[26px] border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div class="relative flex aspect-[16/9] items-center justify-center overflow-hidden bg-gradient-to-br from-sky-100 via-indigo-100 to-slate-100"><img v-if="post.image" :src="post.image" :alt="post.title" class="h-full w-full object-cover transition duration-300 group-hover:scale-105"/><div v-else class="text-center text-indigo-400"><BookOpen class="mx-auto size-14"/><p class="mt-2 text-xs font-bold">CarBooking</p></div></div><div class="flex flex-1 flex-col p-5 sm:p-6"><div class="flex flex-wrap items-center gap-2"><span class="rounded-full bg-indigo-50 px-2.5 py-1 text-[11px] font-bold text-indigo-700">Kinh nghiệm</span><span class="text-xs text-slate-400">{{post.published_at||'Mới cập nhật'}}</span></div><h2 class="mt-3 break-words text-xl font-black leading-7">{{post.title}}</h2><p class="mt-2 line-clamp-3 text-sm leading-6 text-slate-500">{{post.excerpt||'Khám phá những thông tin hữu ích cho hành trình của bạn.'}}</p><div class="mt-auto pt-5"><Link :href="`/blog/${post.slug}`" class="inline-flex items-center gap-2 text-sm font-bold text-indigo-600">Đọc bài viết <ArrowRight class="size-4 transition group-hover:translate-x-1"/></Link></div></div></article></div><div v-else class="rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center"><BookOpen class="mx-auto size-10 text-slate-300"/><h2 class="mt-4 text-xl font-black">Chưa có bài viết</h2><p class="mt-2 text-sm text-slate-500">Nội dung sẽ được cập nhật sớm.</p></div></section>
<section class="mx-auto max-w-7xl px-4 pb-14 sm:px-6 lg:px-8"><div class="grid gap-4 rounded-[28px] bg-indigo-600 p-6 text-white shadow-xl shadow-indigo-600/20 sm:p-8 sm:grid-cols-[1fr_auto] sm:items-center"><div><p class="text-sm font-bold text-indigo-100">Cần chọn xe?</p><h2 class="mt-1 text-2xl font-black">Bắt đầu hành trình ngay hôm nay.</h2><p class="mt-2 max-w-xl text-sm leading-6 text-indigo-100">Không cần tài khoản, không thanh toán online. Gửi yêu cầu và nhận xác nhận trực tiếp.</p></div><Link href="/dat-xe" class="rounded-xl bg-white px-5 py-3 text-center text-sm font-black text-indigo-700">Đặt xe ngay</Link></div></section>
</main>
</div>
</template>
