<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3';
import { ArrowLeft, BookOpen, CarFront, Clock3 } from '@lucide/vue';
interface Post { title:string; excerpt:string|null; content:string; image:string|null; published_at:string|null; }
defineProps<{ post:Post }>();
</script>
<template>
<Head :title="post.title"/>
<div class="min-h-screen bg-slate-50 text-slate-950">
<header class="sticky top-0 z-30 border-b border-slate-200/80 bg-white/95 backdrop-blur"><div class="mx-auto flex min-h-16 max-w-7xl flex-wrap items-center justify-between gap-3 px-4 py-3 sm:px-6 lg:px-8"><Link href="/" class="flex items-center gap-2 font-black"><span class="grid size-9 shrink-0 place-items-center rounded-xl bg-indigo-600 text-white"><CarFront class="size-5"/></span><span>Car<span class="text-indigo-600">Booking</span></span></Link><Link href="/blog" class="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold hover:bg-slate-50"><ArrowLeft class="size-4"/> Blog</Link></div></header>
<main class="mx-auto max-w-5xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8"><Link href="/blog" class="text-sm font-semibold text-indigo-600 hover:text-indigo-700">← Về danh sách bài viết</Link><article class="mt-5 overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-sm"><div v-if="post.image" class="max-h-[520px] overflow-hidden bg-slate-100"><img :src="post.image" :alt="post.title" class="h-full w-full object-cover"/></div><div v-else class="flex aspect-[16/6] items-center justify-center bg-gradient-to-br from-sky-100 via-indigo-100 to-slate-100"><div class="text-center text-indigo-500"><BookOpen class="mx-auto size-14"/><p class="mt-2 text-sm font-bold">CarBooking · Kiến thức di chuyển</p></div></div><div class="mx-auto max-w-3xl p-5 sm:p-8 lg:p-10"><div class="flex flex-wrap items-center gap-3"><span class="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">Kinh nghiệm</span><span class="inline-flex items-center gap-1.5 text-xs text-slate-400"><Clock3 class="size-3.5"/> {{post.published_at||'Mới cập nhật'}}</span></div><h1 class="mt-4 break-words text-3xl font-black leading-tight tracking-tight sm:text-5xl">{{post.title}}</h1><p v-if="post.excerpt" class="mt-5 text-base leading-7 text-slate-500 sm:text-lg">{{post.excerpt}}</p><div class="mt-8 border-t border-slate-100 pt-8"><article class="whitespace-pre-line text-[15px] leading-8 text-slate-700 sm:text-base">{{post.content}}</article></div></div></article><div class="mt-6 flex flex-col gap-4 rounded-[26px] bg-indigo-600 p-6 text-white shadow-xl shadow-indigo-600/20 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm font-bold text-indigo-100">Cần di chuyển?</p><p class="mt-1 text-xl font-black">Đặt xe ngay cho hành trình tiếp theo.</p></div><Link href="/dat-xe" class="rounded-xl bg-white px-5 py-3 text-center text-sm font-black text-indigo-700">Đặt xe</Link></div></main>
</div>
</template>
