<script setup lang="ts">
import { computed, watch } from 'vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
import { ArrowLeft, CalendarDays, CarFront, CheckCircle2, Clock3, MapPin, Route, ShieldCheck, Users } from 'lucide-vue-next';
import AppLayout from '@/layouts/AppLayout.vue';
import type { BreadcrumbItem } from '@/types';

type Vehicle={id:number;name:string;brand:string;model:string;type:string;seats:number;description:string|null;image:string|null;price:number;status:string};
const props=defineProps<{vehicles:Vehicle[];initial:{pickup_location:string;destination:string;travel_date:string;pickup_time:string;passengers:number}}>();
const minDate=new Date().toLocaleDateString('en-CA');
const form=useForm({customer_name:'',phone:'',email:'',pickup_location:props.initial.pickup_location,destination:props.initial.destination,travel_date:props.initial.travel_date,pickup_time:props.initial.pickup_time,passengers:Math.max(1,props.initial.passengers||1),vehicle_id:props.vehicles[0]?.id??null,notes:''});
const selectedVehicle=computed(()=>props.vehicles.find(v=>v?.id===form.vehicle_id)??null);
const passengerLimit=computed(()=>selectedVehicle.value?.seats??60);
watch(passengerLimit,limit=>{if(form.passengers>limit)form.passengers=limit},{immediate:true});
const breadcrumbs:BreadcrumbItem[]=[{title:'Đặt xe',href:'/dat-xe'}];
const submit=()=>form.post('/dat-xe');
</script>
<template>
<AppLayout :breadcrumbs="breadcrumbs"><Head title="Đặt xe"/>
<div class="min-w-0 bg-gradient-to-b from-indigo-50/70 via-background to-background p-3 sm:p-6 lg:p-8">
  <div class="mx-auto max-w-6xl">
    <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
      <div><Link href="/" class="inline-flex items-center gap-1.5 text-sm font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft class="size-4"/> Trang chủ</Link><div class="mt-3 flex items-center gap-3"><span class="grid size-11 place-items-center rounded-2xl bg-primary text-primary-foreground shadow-lg shadow-primary/20"><CarFront class="size-6"/></span><div><p class="text-xs font-bold uppercase tracking-widest text-primary">Đặt chuyến</p><h1 class="text-2xl font-black tracking-tight sm:text-3xl">Đặt xe nhanh chóng</h1></div></div><p class="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Điền thông tin hành trình. Bạn chưa cần tài khoản và chưa cần thanh toán online.</p></div>
      <div class="hidden items-center gap-2 rounded-full border bg-card px-4 py-2 text-xs font-semibold shadow-sm sm:flex"><ShieldCheck class="size-4 text-emerald-600"/> Xác nhận trực tiếp</div>
    </div>
    <div class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]">
      <div class="min-w-0 rounded-3xl border bg-card p-4 shadow-sm sm:p-7">
        <div class="mb-6 flex items-center gap-3 border-b pb-5"><div class="grid size-9 place-items-center rounded-xl bg-primary/10 text-primary font-bold">1</div><div><h2 class="font-bold">Thông tin chuyến đi</h2><p class="text-xs text-muted-foreground">Thông tin liên hệ và lịch trình</p></div></div>
        <form class="grid gap-5" @submit.prevent="submit">
          <div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-1.5 text-sm font-medium">Họ và tên<input v-model="form.customer_name" required maxlength="120" placeholder="Nguyễn Văn A" class="min-w-0 rounded-xl border bg-background px-3.5 py-3"/><span v-if="form.errors.customer_name" class="text-xs text-destructive">{{form.errors.customer_name}}</span></label><label class="grid gap-1.5 text-sm font-medium">Số điện thoại<input v-model="form.phone" required inputmode="tel" placeholder="09xx xxx xxx" class="min-w-0 rounded-xl border bg-background px-3.5 py-3"/><span v-if="form.errors.phone" class="text-xs text-destructive">{{form.errors.phone}}</span></label></div>
          <label class="grid gap-1.5 text-sm font-medium">Email<input v-model="form.email" required type="email" placeholder="email@example.com" class="min-w-0 rounded-xl border bg-background px-3.5 py-3"/><span v-if="form.errors.email" class="text-xs text-destructive">{{form.errors.email}}</span></label>
          <div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-1.5 text-sm font-medium"><span class="flex items-center gap-1.5"><MapPin class="size-4 text-primary"/> Điểm đón</span><input v-model="form.pickup_location" required maxlength="255" placeholder="Địa chỉ đón khách" class="min-w-0 rounded-xl border bg-background px-3.5 py-3"/><span v-if="form.errors.pickup_location" class="text-xs text-destructive">{{form.errors.pickup_location}}</span></label><label class="grid gap-1.5 text-sm font-medium"><span class="flex items-center gap-1.5"><Route class="size-4 text-primary"/> Điểm đến</span><input v-model="form.destination" required maxlength="255" placeholder="Địa chỉ điểm đến" class="min-w-0 rounded-xl border bg-background px-3.5 py-3"/><span v-if="form.errors.destination" class="text-xs text-destructive">{{form.errors.destination}}</span></label></div>
          <div class="grid gap-4 sm:grid-cols-3"><label class="grid gap-1.5 text-sm font-medium">Ngày đi<div class="flex items-center gap-2 rounded-xl border bg-background px-3.5 py-3"><CalendarDays class="size-4 shrink-0 text-primary"/><input v-model="form.travel_date" :min="minDate" required type="date" class="w-full min-w-0 border-0 bg-transparent p-0 text-sm outline-none focus:ring-0"/></div><span v-if="form.errors.travel_date" class="text-xs text-destructive">{{form.errors.travel_date}}</span></label><label class="grid gap-1.5 text-sm font-medium">Giờ đón<div class="flex items-center gap-2 rounded-xl border bg-background px-3.5 py-3"><Clock3 class="size-4 shrink-0 text-primary"/><input v-model="form.pickup_time" required type="time" class="w-full min-w-0 border-0 bg-transparent p-0 text-sm outline-none focus:ring-0"/></div><span v-if="form.errors.pickup_time" class="text-xs text-destructive">{{form.errors.pickup_time}}</span></label><label class="grid gap-1.5 text-sm font-medium">Hành khách<div class="flex items-center gap-2 rounded-xl border bg-background px-3.5 py-3"><Users class="size-4 shrink-0 text-primary"/><input v-model.number="form.passengers" :min="1" :max="passengerLimit" required type="number" class="w-full min-w-0 border-0 bg-transparent p-0 text-sm outline-none focus:ring-0"/></div><span class="text-xs text-muted-foreground">Tối đa {{passengerLimit}} người</span><span v-if="form.errors.passengers" class="text-xs text-destructive">{{form.errors.passengers}}</span></label></div>
          <div class="border-t pt-5"><div class="mb-3 flex items-center gap-3"><div class="grid size-9 place-items-center rounded-xl bg-primary/10 text-primary font-bold">2</div><div><h2 class="font-bold">Chọn xe</h2><p class="text-xs text-muted-foreground">Hoặc để chúng tôi tư vấn xe phù hợp</p></div></div><div class="grid gap-2.5">
            <label class="flex min-w-0 cursor-pointer gap-3 rounded-2xl border p-4 transition hover:bg-accent has-[:checked]:border-primary has-[:checked]:bg-primary/5"><input v-model="form.vehicle_id" :value="null" type="radio" class="mt-1 shrink-0 accent-indigo-600"/><div class="min-w-0"><div class="font-bold">Để chúng tôi tư vấn xe</div><div class="mt-1 text-xs leading-5 text-muted-foreground">Chúng tôi chọn xe phù hợp theo số hành khách và lịch trình.</div></div></label>
            <div v-if="!props.vehicles.length" class="rounded-2xl border border-dashed p-4 text-sm text-muted-foreground">Hiện chưa có xe khả dụng. Bạn vẫn có thể gửi yêu cầu để được tư vấn.</div>
            <label v-for="vehicle in props.vehicles" :key="vehicle.id" class="flex min-w-0 cursor-pointer gap-3 rounded-2xl border p-4 transition hover:bg-accent has-[:checked]:border-primary has-[:checked]:bg-primary/5"><input v-model="form.vehicle_id" :value="vehicle.id" type="radio" class="mt-1 shrink-0 accent-indigo-600"/><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center justify-between gap-2"><div class="truncate font-bold">{{vehicle.name}}</div><span class="shrink-0 rounded-full bg-muted px-2.5 py-1 text-xs font-semibold">{{vehicle.seats}} chỗ</span></div><div class="mt-1 text-xs text-muted-foreground">{{vehicle.brand}} {{vehicle.model}} · {{vehicle.type}}</div><p v-if="vehicle.description" class="mt-1 line-clamp-2 text-sm text-muted-foreground">{{vehicle.description}}</p></div></label>
          </div></div>
          <label class="grid gap-1.5 text-sm font-medium">Ghi chú<textarea v-model="form.notes" maxlength="2000" placeholder="Yêu cầu thêm (nếu có)" class="min-h-24 rounded-xl border bg-background px-3.5 py-3"/></label>
          <div class="flex flex-col-reverse gap-2 border-t pt-5 sm:flex-row sm:justify-end"><Link href="/" class="rounded-xl border px-5 py-3 text-center text-sm font-semibold hover:bg-muted">Hủy</Link><button :disabled="form.processing" type="submit" class="rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground shadow-lg shadow-primary/20 hover:-translate-y-0.5 disabled:opacity-50">{{form.processing?'Đang gửi...':'Gửi yêu cầu đặt xe'}}</button></div>
        </form>
      </div>
      <aside class="min-w-0 lg:sticky lg:top-6 lg:self-start"><div class="overflow-hidden rounded-3xl border bg-slate-950 text-white shadow-xl"><div class="bg-gradient-to-br from-indigo-600/40 to-sky-500/10 p-6"><p class="text-xs font-bold uppercase tracking-widest text-indigo-200">Tóm tắt</p><h2 class="mt-2 text-xl font-black">Hành trình của bạn</h2><div class="mt-5 space-y-4 text-sm"><div class="flex gap-3"><MapPin class="mt-0.5 size-4 shrink-0 text-indigo-300"/><span class="break-words text-slate-300">{{form.pickup_location || 'Chưa nhập điểm đón'}}</span></div><div class="ml-2 h-4 border-l border-dashed border-white/20"></div><div class="flex gap-3"><Route class="mt-0.5 size-4 shrink-0 text-indigo-300"/><span class="break-words text-slate-300">{{form.destination || 'Chưa nhập điểm đến'}}</span></div></div></div><div class="space-y-3 p-6 text-sm"><div class="flex items-center justify-between gap-3"><span class="text-slate-400">Ngày</span><span class="font-semibold">{{form.travel_date || 'Chưa chọn'}}</span></div><div class="flex items-center justify-between gap-3"><span class="text-slate-400">Hành khách</span><span class="font-semibold">{{form.passengers}} người</span></div><div class="flex items-center justify-between gap-3"><span class="text-slate-400">Xe</span><span class="max-w-[55%] truncate text-right font-semibold">{{selectedVehicle?.name || 'Tư vấn xe'}}</span></div><div class="mt-5 rounded-2xl border border-white/10 bg-white/5 p-4 text-xs leading-5 text-slate-400"><CheckCircle2 class="mb-2 size-5 text-emerald-400"/> Gửi yêu cầu hoàn toàn miễn phí. Nhân viên sẽ liên hệ để xác nhận trước khi chốt.</div></div></div></aside>
    </div>
  </div>
</div></AppLayout>
</template>
