<script setup lang="ts">
import { Head, useForm } from '@inertiajs/vue3';
import AppLayout from '@/layouts/AppLayout.vue';
import type { BreadcrumbItem } from '@/types';
type Booking={id:number;customer_name:string;phone:string;email:string;pickup_location:string;destination:string;travel_date:string;pickup_time:string;passengers:number;status:string;vehicle?:{id:number;name:string;brand:string;model:string;seats:number}|null};
const props=defineProps<{bookings:Booking[];filters:{status:string}}>();
const statuses=['pending','confirmed','cancelled','completed'];
const form=useForm({status:''});
const update=(booking:Booking,status:string)=>{form.status=status;form.patch(`/admin/bookings/${booking.id}`)};
const breadcrumbs:BreadcrumbItem[]=[{title:'Đơn đặt xe',href:'/admin/bookings'}];
</script>
<template><AppLayout :breadcrumbs="breadcrumbs"><Head title="Đơn đặt xe"/><div class="min-w-0 space-y-4 p-3 sm:p-6 lg:p-8"><div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 class="text-xl font-semibold">Đơn đặt xe</h1><p class="text-sm text-muted-foreground">Theo dõi và xử lý các yêu cầu đặt xe.</p></div><div class="flex flex-wrap gap-2"><a v-for="status in statuses" :key="status" :href="`/admin/bookings?status=${status}`" class="rounded-md border px-3 py-1.5 text-sm">{{status}}</a></div></div><div class="overflow-x-auto rounded-lg border"><table class="w-full min-w-[1050px] text-sm"><thead><tr class="border-b bg-muted/50 text-left"><th class="p-3">Khách hàng</th><th class="p-3">Hành trình</th><th class="p-3">Ngày / giờ</th><th class="p-3">Xe</th><th class="p-3">Trạng thái</th><th class="p-3">Thao tác</th></tr></thead><tbody><tr v-for="booking in props.bookings" :key="booking.id" class="border-b last:border-0 align-top"><td class="p-3"><div class="font-medium">{{booking.customer_name}}</div><div class="text-xs text-muted-foreground">{{booking.phone}}</div><div class="max-w-[220px] truncate text-xs text-muted-foreground">{{booking.email}}</div></td><td class="max-w-[280px] p-3"><div class="break-words">{{booking.pickup_location}}</div><div class="text-muted-foreground">→ {{booking.destination}}</div></td><td class="whitespace-nowrap p-3">{{booking.travel_date}}<br/>{{booking.pickup_time}}</td><td class="p-3">{{booking.vehicle?.name || 'Chưa phân xe'}}<div class="text-xs text-muted-foreground">{{booking.passengers}} khách</div></td><td class="p-3">{{booking.status}}</td><td class="p-3"><select class="rounded-md border px-2 py-1.5" :value="booking.status" @change="update(booking,($event.target as HTMLSelectElement).value)"><option v-for="status in statuses" :key="status" :value="status">{{status}}</option></select></td></tr><tr v-if="!props.bookings.length"><td colspan="6" class="p-8 text-center text-muted-foreground">Chưa có đơn.</td></tr></tbody></table></div></div></AppLayout></template>
