<script setup lang="ts">
import { Head, useForm } from '@inertiajs/vue3';
import AppLayout from '@/layouts/AppLayout.vue';
import type { BreadcrumbItem } from '@/types';
type Rental={id:number;customer_name:string;phone:string;email:string;pickup_location:string;return_location:string;start_date:string;end_date:string;passengers:number;status:string;vehicle?:{id:number;name:string;brand:string;model:string;seats:number}|null};
const props=defineProps<{rentals:Rental[];filters:{status:string}}>();
const statuses=['pending','confirmed','cancelled','completed'];
const form=useForm({status:''});
const update=(rental:Rental,status:string)=>{form.status=status;form.patch(`/admin/rentals/${rental.id}`)};
const breadcrumbs:BreadcrumbItem[]=[{title:'Đơn thuê xe',href:'/admin/rentals'}];
</script>
<template><AppLayout :breadcrumbs="breadcrumbs"><Head title="Đơn thuê xe"/><div class="min-w-0 space-y-4 p-3 sm:p-6 lg:p-8"><div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 class="text-xl font-semibold">Đơn thuê xe</h1><p class="text-sm text-muted-foreground">Theo dõi và xử lý các yêu cầu thuê xe.</p></div><div class="flex flex-wrap gap-2"><a v-for="status in statuses" :key="status" :href="`/admin/rentals?status=${status}`" class="rounded-md border px-3 py-1.5 text-sm">{{status}}</a></div></div><div class="overflow-x-auto rounded-lg border"><table class="w-full min-w-[1000px] text-sm"><thead><tr class="border-b bg-muted/50 text-left"><th class="p-3">Khách hàng</th><th class="p-3">Thời gian</th><th class="p-3">Địa điểm</th><th class="p-3">Xe</th><th class="p-3">Trạng thái</th><th class="p-3">Thao tác</th></tr></thead><tbody><tr v-for="rental in props.rentals" :key="rental.id" class="border-b last:border-0 align-top"><td class="p-3"><div class="font-medium">{{rental.customer_name}}</div><div class="text-xs text-muted-foreground">{{rental.phone}}</div><div class="max-w-[220px] truncate text-xs text-muted-foreground">{{rental.email}}</div></td><td class="whitespace-nowrap p-3">{{rental.start_date}}<br/>{{rental.end_date}}<div class="text-xs">{{rental.passengers}} khách</div></td><td class="max-w-[240px] p-3 break-words">{{rental.pickup_location}}<br/><span class="text-muted-foreground">→ {{rental.return_location}}</span></td><td class="p-3">{{rental.vehicle?.name || 'Chưa phân xe'}}</td><td class="p-3">{{rental.status}}</td><td class="p-3"><select class="rounded-md border px-2 py-1.5" :value="rental.status" @change="update(rental,($event.target as HTMLSelectElement).value)"><option v-for="status in statuses" :key="status" :value="status">{{status}}</option></select></td></tr><tr v-if="!props.rentals.length"><td colspan="6" class="p-8 text-center text-muted-foreground">Chưa có đơn.</td></tr></tbody></table></div></div></AppLayout></template>
