<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3';
import { CalendarDays, CarFront, Check, ChevronRight, MapPin, Route, Users, ShieldCheck } from 'lucide-vue-next';
import { computed, ref } from 'vue';

const selected = ref('Đà Nẵng – Hội An – Bà Nà');
const guests = ref(4);
const tourDate = ref('');
const pickup = ref('');
const tours = [
 { name:'Đà Nẵng – Hội An – Bà Nà', days:'2N1Đ', route:'Đà Nẵng · Hội An · Bà Nà Hills', destination:'Đà Nẵng – Hội An – Bà Nà', price:'2.490.000đ', desc:'Phù hợp nhóm gia đình và bạn bè.', tone:'from-sky-100 to-indigo-100' },
 { name:'Hà Nội – Ninh Bình – Hạ Long', days:'3N2Đ', route:'Hà Nội · Ninh Bình · Hạ Long', destination:'Hà Nội – Ninh Bình – Hạ Long', price:'3.990.000đ', desc:'Khám phá thiên nhiên và di sản miền Bắc.', tone:'from-emerald-100 to-cyan-100' },
 { name:'Đà Lạt – Tà Nung – Mê Linh', days:'2N1Đ', route:'Đà Lạt · Tà Nung · Mê Linh', destination:'Đà Lạt – Tà Nung – Mê Linh', price:'2.290.000đ', desc:'Nhẹ nhàng, nhiều điểm check-in.', tone:'from-violet-100 to-indigo-100' },
 { name:'Sài Gòn – Vũng Tàu – Hồ Tràm', days:'2N1Đ', route:'TP. Hồ Chí Minh · Vũng Tàu · Hồ Tràm', destination:'Sài Gòn – Vũng Tàu – Hồ Tràm', price:'2.190.000đ', desc:'Đi biển cuối tuần, tối ưu thời gian.', tone:'from-amber-100 to-orange-100' },
];
const selectedTour = computed(() => tours.find((tour) => tour.name === selected.value) ?? tours[0]);
const bookingUrl = computed(() => { const params = new URLSearchParams({ destination:selectedTour.value.destination, passengers:String(guests.value) }); if(tourDate.value) params.set('date', tourDate.value); if(pickup.value.trim()) params.set('pickup', pickup.value.trim()); return `/dat-xe?${params.toString()}`; });
const minDate = new Date().toLocaleDateString('en-CA');
</script>
<template>
<Head title="Đặt xe theo tour"/>
<div class="min-h-screen bg-slate-50 text-slate-950">
<header class="sticky top-0 z-30 border-b border-slate-200/80 bg-white/95 backdrop-blur"><div class="mx-auto flex min-h-16 max-w-7xl flex-wrap items-center justify-between gap-3 px-4 py-3 sm:px-6 lg:px-8"><Link href="/" class="flex items-center gap-2 font-black"><span class="grid size-9 shrink-0 place-items-center rounded-xl bg-indigo-600 text-white"><CarFront class="size-5"/></span><span>Car<span class="text-indigo-600">Booking</span></span></Link><nav class="hidden items-center gap-6 text-sm font-semibold md:flex"><Link href="/" class="hover:text-indigo-600">Trang chủ</Link><Link href="/dat-xe" class="hover:text-indigo-600">Đặt xe</Link><Link href="/thue-xe" class="hover:text-indigo-600">Thuê xe</Link><Link href="/tour" class="text-indigo-600">Theo tour</Link><Link href="/blog" class="hover:text-indigo-600">Blog</Link></nav><Link href="/dat-xe" class="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-indigo-600/20">Đặt xe</Link></div></header>
<main>
<section class="relative overflow-hidden bg-slate-950"><div class="absolute inset-0 bg-[radial-gradient(circle_at_18%_15%,rgba(59,130,246,.3),transparent_30%),radial-gradient(circle_at_85%_25%,rgba(14,165,233,.2),transparent_28%)]"/><div class="relative mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><div class="grid gap-8 lg:grid-cols-[1fr_.78fr] lg:items-center"><div class="text-white"><div class="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-3 py-1.5 text-xs font-bold"><Route class="size-4 text-sky-300"/> HÀNH TRÌNH TRỌN GÓI</div><h1 class="mt-5 text-4xl font-black tracking-tight sm:text-5xl">Chọn tour, chúng tôi lo phần xe.</h1><p class="mt-4 max-w-2xl text-sm leading-7 text-slate-300 sm:text-lg">Một chiếc xe cho cả hành trình: chủ động lịch trình, điểm đón và số khách. Phù hợp gia đình, nhóm bạn và đoàn công tác.</p><div class="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3"><div class="rounded-2xl border border-white/10 bg-white/5 p-4"><CalendarDays class="size-5 text-sky-300"/><p class="mt-3 text-sm font-bold">Lịch linh hoạt</p><p class="mt-1 text-xs text-slate-400">Theo ngày khởi hành</p></div><div class="rounded-2xl border border-white/10 bg-white/5 p-4"><Users class="size-5 text-sky-300"/><p class="mt-3 text-sm font-bold">Xe theo đoàn</p><p class="mt-1 text-xs text-slate-400">Từ nhóm nhỏ đến lớn</p></div><div class="rounded-2xl border border-white/10 bg-white/5 p-4"><ShieldCheck class="size-5 text-emerald-300"/><p class="mt-3 text-sm font-bold">Xác nhận rõ ràng</p><p class="mt-1 text-xs text-slate-400">Không thanh toán online</p></div></div></div><div class="rounded-[28px] border border-white/10 bg-white p-3 shadow-2xl sm:p-4"><div class="flex aspect-[16/10] items-center justify-center rounded-2xl bg-gradient-to-br from-sky-100 via-indigo-100 to-slate-100"><div class="text-center"><div class="mx-auto grid size-20 place-items-center rounded-3xl bg-white shadow-sm sm:size-24"><CarFront class="size-10 text-indigo-500 sm:size-12"/></div><p class="mt-4 text-xl font-black text-slate-800">Xe riêng cho cả chuyến đi</p><p class="mt-1 text-sm text-slate-500">Chọn lịch trình yêu thích bên dưới</p></div></div></div></div></div></section>
<section class="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div class="mb-7 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-bold uppercase tracking-[0.18em] text-indigo-600">Tour nổi bật</p><h2 class="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Đi đâu cũng có xe phù hợp</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Chọn hành trình mẫu, sau đó điều chỉnh ngày đi, điểm đón và số khách.</p></div><span class="text-sm font-semibold text-slate-400">{{ tours.length }} hành trình</span></div><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><button v-for="tour in tours" :key="tour.name" type="button" @click="selected=tour.name" class="group overflow-hidden rounded-[26px] border bg-white text-left shadow-sm transition hover:-translate-y-1 hover:shadow-xl" :class="selected===tour.name?'border-indigo-500 ring-2 ring-indigo-100':'border-slate-200'"><div class="flex aspect-[16/10] items-center justify-center bg-gradient-to-br p-5" :class="tour.tone"><div class="text-center"><div class="mx-auto grid size-14 place-items-center rounded-2xl bg-white/80 shadow-sm"><MapPin class="size-7 text-indigo-500"/></div><span class="mt-3 inline-block rounded-full bg-white/80 px-3 py-1 text-xs font-black">{{tour.days}}</span></div></div><div class="p-5"><div class="flex items-start justify-between gap-3"><h3 class="break-words text-base font-black">{{tour.name}}</h3><span v-if="selected===tour.name" class="rounded-full bg-indigo-600 p-1 text-white"><Check class="size-3"/></span></div><p class="mt-2 text-xs text-slate-500">{{tour.route}}</p><p class="mt-3 text-sm font-bold text-indigo-600">{{tour.price}}<span class="font-medium text-slate-400">/nhóm</span></p></div></button></div></section>
<section class="bg-white"><div class="mx-auto grid max-w-7xl gap-6 px-4 py-12 sm:px-6 lg:grid-cols-[1fr_380px] lg:px-8"><div class="rounded-[28px] border border-slate-200 bg-slate-50 p-5 sm:p-7"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.18em] text-indigo-600">LỊCH TRÌNH BẠN CHỌN</p><h2 class="mt-2 text-2xl font-black sm:text-3xl">{{selectedTour.name}}</h2><p class="mt-2 text-sm leading-6 text-slate-500">{{selectedTour.desc}}</p></div><div class="rounded-2xl bg-white px-4 py-3 text-right shadow-sm"><p class="text-xs text-slate-400">Từ</p><p class="text-lg font-black">{{selectedTour.price}}</p></div></div><div class="mt-7 grid gap-3 sm:grid-cols-3"><div class="rounded-2xl bg-white p-4"><p class="text-xs text-slate-400">Thời lượng</p><p class="mt-1 font-bold">{{selectedTour.days}}</p></div><div class="rounded-2xl bg-white p-4"><p class="text-xs text-slate-400">Lộ trình</p><p class="mt-1 font-bold">{{selectedTour.route}}</p></div><div class="rounded-2xl bg-white p-4"><p class="text-xs text-slate-400">Loại xe</p><p class="mt-1 font-bold">Tư vấn theo đoàn</p></div></div><div class="mt-5 flex items-start gap-3 rounded-2xl border border-indigo-100 bg-indigo-50 p-4 text-sm text-indigo-800"><ShieldCheck class="mt-0.5 size-5 shrink-0"/> Lịch trình và giá cuối cùng sẽ được xác nhận trực tiếp trước khi chốt.</div></div>
<aside class="h-fit rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm sm:p-6 lg:sticky lg:top-20"><p class="text-xs font-bold uppercase tracking-[0.18em] text-indigo-600">ĐẶT TOUR</p><h3 class="mt-2 text-xl font-black">Điều chỉnh hành trình</h3><div class="mt-5 space-y-4"><label class="block"><span class="mb-1.5 block text-xs font-bold text-slate-500">Ngày khởi hành</span><div class="flex items-center gap-2 rounded-2xl bg-slate-50 px-4 py-3"><CalendarDays class="size-5 shrink-0 text-indigo-600"/><input v-model="tourDate" :min="minDate" type="date" class="w-full min-w-0 border-0 bg-transparent p-0 text-sm outline-none focus:ring-0"/></div></label><label class="block"><span class="mb-1.5 block text-xs font-bold text-slate-500">Số khách</span><div class="flex items-center gap-2 rounded-2xl bg-slate-50 px-4 py-3"><Users class="size-5 shrink-0 text-indigo-600"/><select v-model="guests" class="w-full min-w-0 border-0 bg-transparent p-0 text-sm font-semibold outline-none focus:ring-0"><option v-for="n in 16" :key="n" :value="n">{{n}} người</option></select></div></label><label class="block"><span class="mb-1.5 block text-xs font-bold text-slate-500">Điểm đón</span><div class="flex items-center gap-2 rounded-2xl bg-slate-50 px-4 py-3"><MapPin class="size-5 shrink-0 text-indigo-600"/><input v-model="pickup" class="w-full min-w-0 border-0 bg-transparent p-0 text-sm outline-none focus:ring-0" placeholder="Khách sạn / địa chỉ"/></div></label></div><div class="mt-6 border-t border-slate-100 pt-5"><div class="flex items-center justify-between text-sm"><span class="text-slate-500">Khách</span><span class="font-bold">{{guests}} người</span></div><div class="mt-2 flex items-center justify-between text-sm"><span class="text-slate-500">Thời lượng</span><span class="font-bold">{{selectedTour.days}}</span></div><Link :href="bookingUrl" class="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-indigo-600 px-5 py-3.5 text-sm font-bold text-white shadow-lg shadow-indigo-600/20 hover:bg-indigo-500">Tiếp tục đặt xe <ChevronRight class="size-4"/></Link><p class="mt-3 text-center text-xs leading-5 text-slate-400">Thông tin tour được chuyển sang biểu mẫu đặt xe để nhân viên xác nhận.</p></div></aside></div></section>
<section class="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div class="rounded-[28px] bg-indigo-600 p-6 text-white shadow-xl shadow-indigo-600/20 sm:p-8"><div class="grid gap-6 sm:grid-cols-3"><div><p class="text-sm font-bold text-indigo-100">01</p><p class="mt-2 font-black">Chọn hành trình</p><p class="mt-1 text-xs leading-5 text-indigo-100">Chọn tour và số khách phù hợp.</p></div><div><p class="text-sm font-bold text-indigo-100">02</p><p class="mt-2 font-black">Điền ngày & điểm đón</p><p class="mt-1 text-xs leading-5 text-indigo-100">Điều chỉnh theo kế hoạch riêng.</p></div><div><p class="text-sm font-bold text-indigo-100">03</p><p class="mt-2 font-black">Nhân viên xác nhận</p><p class="mt-1 text-xs leading-5 text-indigo-100">Không cần thanh toán online.</p></div></div></div></section>
</main>
</div>
</template>
